### ISSUE TITLE
colorful inline blame when enable font ligatures and blame has CJK text

### ISSUE THREAD

**Issue by transtone** [zielu/GitToolBox#277]
as the title.

![DC71CD04-F4B5-4efb-9336-8B7C052D70B3](https://user-images.githubusercontent.com/46688/100814186-1b16cc00-347c-11eb-8ffe-9fa9e076fbf9.png)
![649BBC87-259A-44a0-8730-699E480EF75E](https://user-images.githubusercontent.com/46688/100814189-1fdb8000-347c-11eb-835a-b013bd75b624.png)

**Comment by transtone** [comment]
![image](https://user-images.githubusercontent.com/46688/100814336-6df08380-347c-11eb-86ff-fbf650828947.png)
![image](https://user-images.githubusercontent.com/46688/100814366-82348080-347c-11eb-83df-916c10cfb021.png)

**Comment by zielu** [comment]
Could you paste in that blame as text ?

**Comment by transtone** [comment]
https://github.com/transtone/blame-test

this repo could test.

the text could be :   测试彩色日志

**Comment by juzi214032** [comment]
I have the same problem

**Comment by zielu** [comment]
@transtone @juzi214032 - could you paste in clipboard output after pressing this button ?

**Comment by transtone** [comment]
> @transtone @juzi214032 - could you paste in clipboard output after pressing this button in About dialog ? It's shown when you hover over left side.
> 
> 
> I don't seem to be able to reproduce this on test repo with vanilla IDE containing only my plugin and on Darkula theme.

maybe you use a non CJK language windows.

**Comment by zielu** [comment]
I'll try retesting under windows with different language combinations

**Comment by sunxyw** [comment]
Same issue here. Any available solution?

**Comment by zielu** [comment]
Depends on IDE version - I have almost completed usage of new API for rendering inline blame that should solve this. But it will be only for 2020.3 and 2021.x IDEs. Ports to 2020.2 it too much effort.

**Comment by sunxyw** [comment]
> 
> 
> Depends on IDE version - I have almost completed usage of new API for rendering inline blame that should solve this. But it will be only for 2020.3 and 2021.x IDEs. Ports to 2020.2 it too much effort.

I am using PHPStorm 2021.1.4 and GitToolBox 203.5.10, this issue still exists.
![圖片](https://user-images.githubusercontent.com/31698606/125936488-2a9436c3-0632-431b-8fa1-1ff76f5bd8db.png)
![圖片](https://user-images.githubusercontent.com/31698606/125936677-c26794eb-0bc1-438e-bb7f-af8b2c922553.png)

**Comment by zielu** [comment]
@sunxyw Can you switch to EAP channel (as described here https://github.com/zielu/GitToolBox#eap-builds) and try with 203.7.0 ?

**Comment by sunxyw** [comment]
> 
> 
> @sunxyw Can you switch to EAP channel (as described here https://github.com/zielu/GitToolBox#eap-builds) and try with 203.7.0 ?

I updated to 203.7.0 but it still exists.
![圖片](https://user-images.githubusercontent.com/31698606/127118500-9bfe4915-b443-474d-8646-081b72b17613.png)

**Comment by zielu** [comment]
One more setting to change: Preferences > Version Control > GitToolBox > Blame tab - Style > Inlay

**Comment by sunxyw** [comment]
@zielu The color appears correctly now. But it seems that it can't display the characters.
The blank box should be "初始化项目".

![圖片](https://user-images.githubusercontent.com/31698606/127120119-e7bc4329-efa3-49c2-8290-ac5d7220a589.png)

**Comment by zielu** [comment]
Ok thanks for trying, looks like I will need to look into unicode rendering

**Comment by sunxyw** [comment]
@zielu Jetbrains Mono

![圖片](https://user-images.githubusercontent.com/31698606/127122356-1c651542-d100-43c2-abaf-0c77210358f0.png)

**Comment by zielu** [comment]
@sunxyw I cannot reproduce it :/ - which OS are you using ?

**Comment by sunxyw** [comment]
@zielu Win10 21H1 (Build 19043.1110)

**Comment by zielu** [comment]
@sunxyw also please share locale you are using

**Comment by sunxyw** [comment]
@zielu In the order of setting:

- Chinese (Traditional, Taiwan)
- Chinese (Simplified, China)
- English (US)
- Japanese

Screenshot of Setting > Time & Language > Language:
![圖片](https://user-images.githubusercontent.com/31698606/127141695-5f72a4b8-8189-49b0-adf0-bcdee7febcd2.png)

**Comment by zielu** [comment]
I managed to reproduce it with legacy rendering mode on fresh Windows 10 install even on default english locale on blame-test project.
<img width="836" alt="image" src="https://user-images.githubusercontent.com/464103/127211406-439ceb89-6039-434f-a7c3-6e7cbbbc7027.png">

**Comment by zielu** [comment]
Boxes instead of letters with inlay rendering mode too:
<img width="836" alt="image" src="https://user-images.githubusercontent.com/464103/127211669-4042dbbe-91c2-476a-8bca-2f513f5dc665.png">

**Comment by zielu** [comment]
Looks like it is a "windows thing" - I think I have enough to investigate now :)

**Comment by sunxyw** [comment]
Thank you for your time and effort. Please take your time, this is not an urgent matter.

**Comment by zielu** [comment]
@sunxyw you can try 203.7.1 from EAP channel - it should be good now with Inlay style.

**Comment by sunxyw** [comment]
@zielu Yes. It works well now. Thank you for your help.

**Comment by zielu** [comment]
Done in (203/212).7.4
