### ISSUE TITLE
Extreme slowdown on startup

### ISSUE THREAD

**Issue by kad-molenj** [zielu/GitToolBox#290]
I usually work with one big project containing ~35 modules with their own git repository.
When I start Intellij IDEA with the plugin enabled my system slows down so much that even my mousepointer becomes unresponsive (delayed movement). This takes about a minute. It does not happen with the plugin disabled.

I believe this behaviour started somewhere around 

> Changes in 202.2.0
> Fix: Blame status bar updated when caret is placed inside test console window
> Fix: Exceptions in Push tags on branch (#269)
> Arch: Blame cache persistence (#217)
> Arch: Replace Platform thread pools with dedicated ones

Although I am not entirely certain when exactly. I do know that a couple months ago I did not have startup issues with the plugin enabled.

I hope this can be fixed because I really enjoyed the plugin until it started slowing down my system to a crawl!

**Comment by zielu** [comment]
Hi, I'll take a look.

**Comment by zielu** [comment]
@kad-molenj let's see if it's caused by blame cache persistence - please find config described in https://github.com/zielu/GitToolBox/wiki/Manual#registry-switches, disable it and restart.

**Comment by kad-molenj** [comment]
@zielu Thanks for looking into this!
I disabled the blame cache persistence but that did not change anything, unfortunately.

**Comment by zielu** [comment]
@kad-molenj IDE creates thread dumps alongside logs when there are some freezes - you should be able to access log directory with `Help / Show Log in...` or smth similiar. Grab first file from `threadDump-freeze...` directory corresponding to startup moment or better yet. Shutdown IDE delete all threadDumps, start and share one that IDE should create.

**Comment by kad-molenj** [comment]
I deleted the older logs. However, no new thread dumps are created. I suppose it doesn't count as a freeze although my machine is definitely unusable for a good while.

I attached the application logging from startup, maybe there's a hint in there?
[idea.log](https://github.com/zielu/GitToolBox/files/5873415/idea.log)

**Comment by zielu** [comment]
Thanks ! I see there are lot's of auto-fetch requests running. Let's try to eliminate this factor too. Could you disable Auto-fetch in GitToolBox Project settings ? 
You will have to restart, because there is a bug related to that setting not being applied that I'm fixing right now.

**Comment by kad-molenj** [comment]
Yeah without auto-fetch I don't experience any startup problems.
Auto-fetch never caused any trouble before either, that is, after the IDE had been fully started up.

I will have to manually do a fetch/pull to see the latest state but I suppose that's much better than not using the plugin at all!

**Comment by zielu** [comment]
I'll reexamine that part of code - it's actually one of the oldest areas so I might be able to squeeze out some more performance out of it or at very least make first auto-fetch more smooth. There is already a small delay to give project some time to "settle", but in case of this number of repositories it has to be smarter.

**Comment by kad-molenj** [comment]
Thank you for looking into it, and for your quick replies!

**Comment by zielu** [comment]
@kad-molenj I added alternative mechanism for first auto-fetch - it will wait until all state is initialised so there should be less pressure on running concurrent git operations.
I pushed early access release to EAP channel, if you are feeling brave you can give it a try.
To switch to EAP channel, follow https://github.com/zielu/GitToolBox#eap-builds.
Then in `Registry` there is new key added that must be enabled to try new logic: `zielu.gittoolbox.fetch.auto.debounce.first`

**Comment by kad-molenj** [comment]
I added the EAP plugin repository, enabled the new key in the registry and re-enabled auto-fetch. 
Then I restarted... Alas, the problem persists. It did wait a little longer before fetching on all repos. Perhaps the slowdown was slightly less, but it's hard to tell.
Surprisingly, the auto-fetch doesn't seem to have any problems on consecutive fetches. Perhaps it's because the fetching is staggered instead of simultaneous after the first one? That would only make sense only if the auto-fetch timer is per-repository.

**Comment by zielu** [comment]
Hmm, so I seems it needs more investigation. What is curious is that it's always running same code and there is only one timer. I'll need to dive into IDE util that does the fetching.

**Comment by kad-molenj** [comment]
I must say, after one of the latest updates (I think 203.4.3) I tried re-enabling auto-fetch and the slowdown on startup isn't so bad anymore! I don't know why it didn't work when I selected the change from the EAP channel.

**Comment by zielu** [comment]
Hi, I was tweaking things in the background. Now instead of fetching right away after 10sec elapsed since project open there is first wait for all things to initialize and then time to start fetching depends on number of repositories so in your case it gives even more time.

**Comment by zielu** [comment]
I'll close it for now, there are some more improvements possible but I'd add them as separate ticket.
